from characters_class import Personaje


Albedo = Personaje('Mondstadt', 'Sword', 'Geo', 'Male', '5', 'Albedo')
Alhaitham = Personaje('Sumeru', 'Sword', 'Dendro', 'Male', '5', 'Alhaitham')
Aloy = Personaje('None', 'Bow', 'Cryo', 'Female', '5', 'Aloy')
Amber = Personaje('Mondstadt', 'Bow', 'Pyro', 'Female', '4', 'Amber')
Arattaki_Itto = Personaje('Inazuma', 'Claymore', 'Geo', 'Male', '5', 'Arattaki Itto')
Arlecchino = Personaje('Fontaine', 'Polearm', 'Pyro', 'Female', '5', 'Arlecchino')
Baizhu = Personaje('Liyue', 'Catalyst', 'Dendro', 'Male', '5', 'Baizhu')
Barbara = Personaje('Mondstadt', 'Catalyst', 'Hydro', 'Female', '4', 'Barbara')
Beidou = Personaje('Liyue', 'Claymore', 'Electro', 'Female', '4', 'Beidou')
Bennett = Personaje('Mondstadt', 'Swords', 'Pyro', 'Male', '4', 'Bennett')
Candace = Personaje('Sumeru', 'Polearm', 'Hydro', 'Female', '4', 'Candace')
Charlote = Personaje('Fontaine', 'Catalyst', 'Cryo', 'Female', '4', 'Charlote')
Chevereuse =  Personaje('Fontaine', 'Polearm', 'Pyro','Female', '4', 'Chevereuse')
Chiori = Personaje('Inazuma', 'Sword', 'Geo', 'Female', '5', 'Chiori')
Chongyun = Personaje('Liyue', 'Claymore', 'Cryo', 'Male', '4', 'Chongyun')
Clorinde = Personaje('Fontaine', 'Sword', 'Electro', 'Female', '5', 'Clorinde')
Collei = Personaje('Sumeru', 'Bow', 'Dendro', 'Female', '4', 'Collei')
Cyno = Personaje('Sumeru', 'Polearm', 'Electro', 'Male', '5', 'Cyno')
Dehya = Personaje('Sumeru', 'Claymore', 'Pyro', 'Female', '5', 'Dehya')
Diluc = Personaje('Mondstadt', 'Claymore', 'Pyro', 'Male', '5', 'Diluc')
Diona = Personaje('Mondstadt', 'Bow', 'Cryo', 'Female', '4', 'Diona')
Diori = Personaje('Sumeru', 'Claymore', 'Electro', 'Female', '4', 'Diori')
Eula = Personaje('Mondstadt', 'Claymore', 'Cryo', 'Female', '5', 'Eula')
Faruzan = Personaje('Sumeru', 'Bow', 'Anemo', 'Female', '4', 'Faruzan')
Fischl = Personaje('Mondstadt', 'Bow', 'Electro', 'Female', '4', 'Fischl')
Freminet = Personaje('Fontaine', 'Claymore', 'Cryo', 'Male', '4', 'Freminet')
Furina = Personaje('Fontaine', 'Sword', 'Hydro', 'Female', '5', 'Furina')
Gaming = Personaje('Liyue', 'Claymore', 'Pyro', 'Male', '4', 'Gaming')
Ganyu = Personaje('Liyue', 'Bow', 'Cryo', 'Female', '5', 'Ganyu')
Gorou = Personaje('Inazuma', 'Bow', 'Geo', 'Male', '4', 'Gorou')
Hu_Tao = Personaje('Liyue', 'Polearm', 'Pyro', 'Female', '5', 'Hu Tao')
Jean = Personaje('Mondstadt', 'Sword', 'Anemo', 'Female', '5', 'Jean')
Kaedehara_Kazuha = Personaje('Inazuma', 'Sword', 'Anemo','Male', '5', 'Kazuha')
Kaeya = Personaje('Mondstadt', 'Sword', 'Cryo', 'Male', '4', 'Kaeya')
Kamisato_Ayaka = Personaje("Inazuma", 'Sword', 'Cryo', 'Female', '5', 'Ayaka')
Kamisato_Ayato = Personaje('Inazuma', 'Sword', 'Hydro', 'Male', '5', 'Ayato')
Kaveh = Personaje('Sumeru', 'Claymore', 'Dendro', 'Male', '4', 'Kaveh')
Keqing = Personaje('Liyue', 'Sword', 'Electro', 'Female', '5', 'Keqing')
Kirara = Personaje('Inazuma', 'Sword', 'Dendro', 'Female', '4', 'Kirara')
Klee = Personaje('Mondstadt', 'Catalyst', 'Pyro', 'Female', '5', 'Klee')
Kujou_Sara = Personaje('Inazuma', 'Bow', 'Electro', 'Female', '4', 'Kujou Sara')
Kuki_Shinobu = Personaje('Inazuma', 'Sword', 'Electro', 'Female', '4', 'Kuki')
Laila = Personaje('Sumeru', 'Sword', 'Cryo', 'Female', '4', 'Laila')
Lisa = Personaje('Mondstadt', 'Catalyst', 'Electro', 'Female', '4', 'Lisa')
Lynette = Personaje('Fontaine', 'Sword', 'Anemo', 'Female', '4', 'Lynette')
Lyney = Personaje('Fontaine', 'Bow', 'Pyro', 'Male', '5', 'Lyney')
Mika = Personaje('Mondstadt', 'Polearm', 'Cryo', 'Male', '4', 'Mika')
Mona = Personaje('Mondstadt', 'Catalyst', 'Hydro', 'Female', '5', 'Mona')
Nahida = Personaje('Sumeru', 'Catalyst', 'Dendro', 'Female', '5', 'Nahida')
Navia = Personaje('Fontaine', 'Claymore', 'Geo', 'Female', '5', 'Navia')
Neuvillette = Personaje('Fontaine', 'Catalyst', 'Hydro', 'Male', '5', 'Neuvillette')
Nilou = Personaje('Sumeru', 'Sword', 'Hydro', 'Female', '5', 'Nilou')
Ningguang = Personaje('Liyue', 'Catalyst', 'Geo', 'Female', '4', 'Ningguang')
Noelle = Personaje('Mondstadt', 'Claymore', 'Geo', 'Female', '4', 'Noelle')
Qiqi = Personaje('Liyue', 'Sword', 'Cryo', 'Female', '5', 'Qiqi')
Raiden_Shogun = Personaje('Inazuma', 'Polearm', 'Electro', 'Female', '5', 'Raiden Shogun')
Razor = Personaje('Mondstadt', 'Claymore', 'Electro', 'Male', '4', 'Razor')
Rosaria = Personaje('Mondstadt', 'Polearm', "Cryo", 'Female', '4', 'Rosaria')
Sangonomiya_Kokomi = Personaje('Inazuma', 'Catalyst', 'Hydro', 'Female', '5', 'Kokomi')
Sayu = Personaje('Inazuma', 'Claymore', 'Anemo', 'Female', '4', 'Sayu')
Sethos = Personaje('Sumeru', 'Bow', 'Electro', 'Male', '4', 'Sethos')
Shenhe = Personaje('Liyue', 'Polearm', 'Cryo', 'Female', '5', 'Shenhe')
Shikanoin_Heizou = Personaje('Inazuma', 'Catalyst', 'Anemo', 'Male', '4', 'Heizou')
Sigewinne = Personaje('Fontaine', 'Bow', 'Hydro', 'Female', '5', 'Sigewinne')
Sucrose = Personaje('Mondstadt', 'Catalyst', 'Anemo', 'Female', '4', 'Sucrose')
Tartaglia = Personaje('Snezhnaya', 'Bow', 'Hydro', 'Male', '5', 'Tartaglia')
Thoma = Personaje('Inazuma', 'Polearm', 'Pyro', 'Male', '4', 'Thoma')
Tighnari = Personaje('Sumeru', 'Bow', 'Dendro', 'Male', '5', 'Tighnari')
Traveler = Personaje('None', 'Sword', 'All', 'Both', '5', 'Traveler')
Venti = Personaje('Mondstadt', 'Bow', 'Anemo', 'Male', '5', 'Venti')
Wanderer = Personaje('Inazuma', 'Catalyst', 'Anemo', 'Male', '5', 'Wanderer')
Wriothesley = Personaje('Fontaine', 'Catalyst', 'Cryo', 'Male', '5', 'Wriothesley')
Xiangling = Personaje('Liyue', 'Polearm', 'Pyro', 'Female', '4', 'Xiangling')
Xianyun = Personaje('Liyue', 'Catalyst', 'Anemo', 'Female', '5', 'Xianyun')
Xiao = Personaje('Liyue', 'Polearm', 'Anemo', 'Male', '5', 'Xiao')
Xingqiu = Personaje('Liyue', 'Sword', 'Hydro', 'Male', '4', 'Xingqiu')
Xinyan = Personaje('Liyue', 'Claymore', 'Pyro', 'Female', '4', 'Xinyan')
Yae_Miko = Personaje('Inazuma', 'Catalyst', 'Electro', 'Female', '5', 'Yae Miko')
Yanfei = Personaje('Liyue', 'Catalyst', 'Pyro', 'Female', '4', 'Yanfei')
Yaoyao = Personaje('Liyue', 'Polearm', 'Dendro', 'Female', '4', 'Yaoyao')
Yelan = Personaje('Liyue', 'Bow', 'Hydro','Female', '5', 'Yelan')
Yoimiya = Personaje('Inazuma', 'Bow', 'Pyro', 'Female', '5', 'Yoimiya')
Yun_Jin = Personaje('Liyue', 'Polearm', 'Geo', 'Female', '4', 'Yun Jin')
Zhongli = Personaje('Liyue', 'Polearm', 'Geo', 'Male', '5', 'Zhongli')
Mizuki = Personaje('Inazuma', 'Catalyst', 'Anemo', 'Female', '5', 'Mizuki')
Lan_Yan = Personaje('Liyue', 'Catalyst', 'Anemo', 'Female', '4', 'Lan Yan' )
Citlali = Personaje('Natlan', 'Catalyst', 'Cryo', 'Female', '5', 'Citlali')
Mavuika = Personaje('Natlan', 'Claymore', 'Pyro', 'Female', '5', 'Mavuika')
Chaska = Personaje('Natlan', 'Bow', 'Anemo', 'Female', '5', 'Chaska')
Ororon = Personaje('Natlan', 'Bow', 'Electro', 'Male', '4', 'Ororon')
Xilonen = Personaje('Natlan', 'Sword', 'Geo', 'Female', '5', 'Xilonen')
Kinich = Personaje('Natlan', 'Claymore', 'Dendro', 'Male', '5', 'Kinich')
Kachina = Personaje('Natlan', 'Polearm', 'Geo', 'Female', '4', 'Kachina')
Mualani = Personaje('Natlan', 'Catalyst', 'Hydro', 'Female', '5', 'Mualani')
Emilie = Personaje('Fontaine', 'Polearm', 'Dendro', 'Female', '5', 'Emilie')

Personajes_List = [Albedo, Alhaitham, Aloy, Amber, Arattaki_Itto, Arlecchino, Baizhu, 
    Barbara, Beidou, Bennett, Candace, Charlote, Chevereuse, Chiori, Chongyun, Clorinde,
    Collei, Cyno, Dehya, Diluc, Diona, Diori, Eula, Faruzan, Fischl, Freminet, Furina, Gaming,
    Ganyu, Gorou, Hu_Tao, Jean, Kaedehara_Kazuha, Kaeya, Kamisato_Ayaka, Kamisato_Ayato,
    Kaveh, Keqing, Kirara, Klee, Kujou_Sara, Kuki_Shinobu, Laila, Lisa, Lynette, Lyney, Mika,
    Mona, Nahida, Navia, Neuvillette, Nilou, Ningguang, Noelle, Qiqi, Raiden_Shogun, Razor,
    Rosaria, Sangonomiya_Kokomi, Sayu, Sethos, Shenhe, Shikanoin_Heizou, Sigewinne, Sucrose,
    Tartaglia, Thoma, Tighnari, Traveler, Venti, Wanderer, Wriothesley, Xiangling, Xianyun, 
    Xiao, Xingqiu, Xinyan, Yae_Miko, Yanfei, Yaoyao, Yelan, Yoimiya, Yun_Jin, Zhongli, Mizuki,
    Lan_Yan, Citlali, Mavuika, Chaska, Ororon, Xilonen, Kinich, Kachina, Mualani, Emilie]
